### ISSUE TITLE
doesnt allow negative values

### ISSUE THREAD

**Issue by lelnofake** [Equbuxu/mine#9]

**Comment by Equbuxu** [comment]
Where are you putting negative values

**Comment by lelnofake** [comment]
in the height of cube

**Comment by Equbuxu** [comment]
hmm, I guess I'll have to test this

Btw, it's not in the readme, but if you know lua you can write your own scripts to mine an area of any shape. For example there is a `cylinder.lua` script which can be called via `custom cylinder.lua`. You can make new scripts like that or edit cylinder.lua.

**Comment by Equbuxu** [comment]
Just tested this (only took me a year, lol), `cube` works fine with negative values. Were you running `rcube` by any chance? `rcube` doesn't support negative values, because `rcube` mines a cuboid centered on the turtle, so each dimension is a "radius", it doesn't make sense for it to be negative

Tip: you can use `help <programname>` (e.g. `help rcube`) to see a description of what the program does
